### ISSUE TITLE
The remote server returned an error

### ISSUE THREAD

**Issue by Ayanmullick** [dfinke/InstallModuleFromGitHub#10]
I'm unable to get this to work. I have a 'Hello World' test module in my Github repository but get an error

**Cmdlet** :
`Install-ModuleFromGitHub -GitHubRepo /AyanMullick/test/master/HelloWorld.psm1`

**Error**: 
`Invoke-RestMethod : The remote server returned an error: (404) Not Found.
At C:\Program files\WindowsPowerShell\Modules\InstallModuleFromGitHub\1.1\InstallModuleFromGitHub.psm1:40 char:19                  Invoke-RestMethod $url -OutFile $OutFile`

**Comment by dfinke** [comment]
What version of PowerShell are you running?

**Comment by Ayanmullick** [comment]
5.1

**Comment by Ayanmullick** [comment]
Using this for now

```ps
$User     = 'Ayanmullick'
$Repo     = 'test'
$Module   = 'HelloWorld'                                                                                                                         #Replace with Script name
$DestPath= New-Item -Path ([Environment]::GetFolderPath('MyDocuments')+"\PowerShell\Modules")  -Name $Module -ItemType "directory"               #Create directory in User's default Module folder                                                                   
(New-Object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/$User/$Repo/master/$Module.psm1","$DestPath\$Module.psm1")     #Download module
```
