### ISSUE TITLE
Fix module installation path

### ISSUE THREAD

**Issue by JonathanPitre** [dfinke/InstallModuleFromGitHub#16]
There's an issue with the latest release.  The installation path for the module is wrong. It contains the parent folder instead of just the content of the archive.

![image](https://user-images.githubusercontent.com/15003329/79147878-a8dd6400-7d92-11ea-8669-90c998ea88ae.png)

Here's the fix:

Line 82
`$null = Copy-Item "$(Join-Path -Path $tmpDir -ChildPath $unzippedArchive\*)" $dest -Recurse -Force`

**Comment by dfinke** [comment]
Thanks. I published this from my new machine with the same workflow. I'll publish it from the old box and investigate.

**Comment by dfinke** [comment]
Installed from the gallery, couldn't repro.

![image](https://user-images.githubusercontent.com/67258/79167559-afc99e00-7db5-11ea-8446-f57653de455a.png)

**Comment by JonathanPitre** [comment]
Try this

`Install-ModuleFromGitHub -GitHubRepo JonathanPitre/PSAppDeployToolkit`

**Comment by dfinke** [comment]
Sorry, thought it was doing it from the gallery. Not sure when I'll be able to get to this. If you figure out, submit a PR.

**Comment by JonathanPitre** [comment]
The fix is simply to change line 81 to this:
` $null = Copy-Item "$(Join-Path -Path $tmpDir -ChildPath $unzippedArchive\*)" $dest -Force `-Recurse`

I tried to create a pull reques but I keep gettting an error. 

> fatal: TypeLoadException encountered.
>    Method 'DeleteCredentials' in type 'Atlassian.Bitbucket.Authentication.Authentication' from assembly 'Bitbucket.Authentication, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
> remote: Permission to dfinke/InstallModuleFromGitHub.git denied to JonathanPitre.

**Comment by dfinke** [comment]
Fixed by #18
