### ISSUE TITLE
Add -DestinationPath as an option

### ISSUE THREAD

**Issue by dfinke** [dfinke/InstallModuleFromGitHub#2]
Let the user put it where they want to

**Comment by chriswahl** [comment]
This would be a wonderful enhancement. I prefer to drop the Modules into my OneDrive path but find them being dropped into the ProgramFiles directory.

**Comment by dfinke** [comment]
Added https://github.com/dfinke/InstallModuleFromGitHub/commit/482e30515f6b4ebcb25530c4ce2ecceb08c4a4c3
